language: java
jdk:
  - oraclejdk8
#image: git.cs.sun.ac.za:4567/deepsea/deepsea/alpine-jdk8-git
## image: localhost:5000/git-jdk-alpine
#before_script:
#  - echo `pwd`
#  - export GRADLE_USER_HOME=`pwd`/.gradle
#  - rm -f  .gradle/caches/modules-2/modules-2.lock
#  - rm -fr .gradle/caches/*/plugin-resolution/
#cache:
#  paths:
#    - .gradle/wrapper
#    - .gradle/caches
#build:
#  script:
#    - ./gradlew clean installDist javadoc
#  artifacts:
#    paths:
#      - build/docs/javadoc
#      - build/install/deepsea/lib/*.jar
#      - build/resources/main
#    expire_in: 4 weeks
