#!/bin/sh
# Starts 3 (THREE) virtualbox-based docker machines

docker-machine create --driver virtualbox myvm1
docker-machine create --driver virtualbox myvm2
docker-machine create --driver virtualbox myvm3
IP=`docker-machine ip myvm1`
docker-machine ssh myvm1 "docker swarm init --advertise-addr ${IP}"
docker-machine ssh myvm1 "docker swarm join-token --quiet manager"
TOKEN=`docker-machine ssh myvm1 "docker swarm join-token --quiet manager"`
echo ${TOKEN}
echo docker-machine ssh myvm2 "docker swarm join --token ${TOKEN} ${IP}:2377"
echo docker-machine ssh myvm3 "docker swarm join --token ${TOKEN} ${IP}:2377"
